# Generated by Django 5.1.4 on 2024-12-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(max_length=255, unique=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "shipping_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_address_line1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_address_line2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_city",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_state",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_postal_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "shipping_country",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                ("subtotal_cents", models.IntegerField()),
                ("total_cents", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant_id", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="stripe.order",
                    ),
                ),
            ],
        ),
    ]
