# Generated by Django 5.1.4 on 2024-12-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
