# Generated by Django 5.1.4 on 2024-12-13 19:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe", "0002_alter_order_id_alter_orderitem_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
