# Generated by Django 5.1.4 on 2024-12-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="email verification token",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token_created_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="email verification token created at",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="email verified"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "This email is already in use."},
                max_length=255,
                unique=True,
            ),
        ),
    ]
