# Generated by Django 5.1.4 on 2024-12-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_email_verification_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="password reset token",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="password reset token created at"
            ),
        ),
    ]
