# Generated by Django 5.1.4 on 2024-12-09 22:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="shirt",
            name="sku",
        ),
    ]
