# Generated by Django 5.1.4 on 2024-12-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_productimage_options_remove_shirt_colors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shirt",
            name="available_options",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Available options for this product. Format: {'sizes': ['S', 'M', 'L'], 'colors': ['Red', 'Blue']}",
                null=True,
            ),
        ),
    ]
