# Generated by Django 5.1.4 on 2024-12-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_shirt_available_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Navy Blue, Forest Green", max_length=50
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. navy, forest-green", max_length=50
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Small, Medium, Large", max_length=50
                    ),
                ),
                ("code", models.CharField(help_text="e.g. S, M, L, XL", max_length=10)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RemoveField(
            model_name="shirt",
            name="available_options",
        ),
        migrations.RemoveField(
            model_name="shirt",
            name="default_variant_name",
        ),
        migrations.AddField(
            model_name="shirt",
            name="available_colors",
            field=models.ManyToManyField(blank=True, to="products.color"),
        ),
        migrations.AddField(
            model_name="shirt",
            name="available_sizes",
            field=models.ManyToManyField(blank=True, to="products.size"),
        ),
    ]
