# Generated by Django 5.1.4 on 2024-12-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_color_size_remove_shirt_available_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shirt",
            name="name",
            field=models.CharField(default="unnamed", max_length=255),
            preserve_default=False,
        ),
    ]
