# Generated by Django 5.1.4 on 2024-12-09 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_artwork_name_shirt_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shirt",
            name="available_colors",
        ),
        migrations.DeleteModel(
            name="Color",
        ),
    ]
