# Generated by Django 5.1.4 on 2024-12-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_delete_artwork_delete_artworktype"),
    ]

    operations = [
        migrations.AddField(
            model_name="shirt",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
