# Generated by Django 5.1.4 on 2024-12-11 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("products", "0011_shirt_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shirttype",
            options={},
        ),
        migrations.CreateModel(
            name="ProductShippingCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.UUIDField()),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("price_cents", models.IntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("content_type", "object_id", "country")},
            },
        ),
    ]
