# Generated by Django 5.1.4 on 2024-12-11 21:55

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_alter_productshippingcost_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productshippingcost",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Leave empty for 'Rest of World' rate",
                max_length=2,
                null=True,
                unique=True,
            ),
        ),
    ]
